In [1]:
import sys

sys.path.append("corona")
from src import utils

In [4]:
df, dt = utils.pull_latest_data()

############
Data Ingest
############
UTC date and time: 2020-04-13 04:02:58
Dataset pulled from: https://opendata.ecdc.europa.eu/covid19/casedistribution/csv

In [5]:
df

,date_rep,day,month,year,cases,deaths,countries_and_territories,geo_id,countryterritory_code,pop_data2018,date
0,12/04/2020,12,4,2020,34,3,Afghanistan,AF,AFG,37172386.0,2020-04-12
1,11/04/2020,11,4,2020,37,0,Afghanistan,AF,AFG,37172386.0,2020-04-11
2,10/04/2020,10,4,2020,61,1,Afghanistan,AF,AFG,37172386.0,2020-04-10
3,09/04/2020,9,4,2020,56,3,Afghanistan,AF,AFG,37172386.0,2020-04-09
4,08/04/2020,8,4,2020,30,4,Afghanistan,AF,AFG,37172386.0,2020-04-08
...,...,...,...,...,...,...,...,...,...,...,...
10327,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0,2020-03-25
10328,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14439018.0,2020-03-24
10329,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14439018.0,2020-03-23
10330,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0,2020-03-22
10331,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14439018.0,2020-03-21